import '@/styles/globals.css';

// import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';

import { Toaster } from '@/components/ui/toaster';
import { getServerAuthSession } from '@/server/auth';
import { Providers, RenderLayout } from '@/components/layout';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();

  return (
    <html
      lang="en"
      // className={`${GeistSans.variable}`}
      suppressHydrationWarning={true}
    >
      <body>
        <Providers session={session}>
          <NextTopLoader showSpinner={false} />
          <Toaster />
          <RenderLayout>{children}</RenderLayout>
        </Providers>
      </body>
    </html>
  );
}
